name: eduline
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  get:
  smooth_page_indicator:
  flutter_svg: 
  flutter_spinkit: 
  pinput: 
  geolocator: 
  permission_handler: 
  shared_preferences:
  get_storage:
  loading_animation_widget: ^1.3.0
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.1
  http: ^1.5.0
  flutter_screenutil: ^5.9.3
  flutter_staggered_grid_view: ^0.7.0
  unsplash_client: ^3.0.0
  flutter_easyloading: ^3.0.5
  flutter_dotenv: ^5.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf